[project]
name = "inverse-problem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=6.0.0",
    "deepinv[dataset,denoisers]>=0.3.7",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "mystmd>=1.8.0",
    "numba>=0.63.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "polars>=1.37.1",
    "pyarrow>=23.0.0",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "vegafusion>=2.0.3",
]

[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.lint.pycodestyle]
max-line-length = 320

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN204",  # missing class init return type
    "COM812",  # missing-trailing-comma, is already handled by ruff formatting
    "C408",    # unnecessary-collection-call 
    "C420",    # unnecessary-dict-comprehension
    "D1",      # docstring-missing 
    "D202",    # blank-line-before-function
    "D203",    # blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "D401",    # docstring should be in imperative mood
    "E402",    # module level import not at top of file
    "ERA001",  # Allow commented out code 
    "N803",    # Allow non-lowercase argument names (e.g., fit(X, y))
    "N806",    # Allow non-lowercase variables in functions (e.g., Matrix X)
    "N816",    # mixed-case-variable-in-global-scope
    "PLR2004", # magic-value-comparison
    "T201",    # print-statement
    "S113",    # requests call without timeout
    "RUF001",  # ambiguous-unicode-character-string
    "RUF002",  # ambiguous-unicode-character-docstring
    "RUF003",  # ambiguous-unicode-character-comment
    "RET504",  # return-statement
]
